[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["wireguard-tools", "iproute2", "iptables"]

[deploy]
startCommand = "bash /app/start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
