[Interface]
Address = 10.100.31.80/32
PrivateKey = oMqED6lesxjWMlGbd6gG216TUbG+ZUk7D8aHnLF2Om8=
MTU = 1298
DNS = 10.100.16.7

[Peer]
PublicKey = fJJu3mg8FNuERB4fE7gPuJIvZw7Lcq5vWLq/k8U4vxg=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = ingrs-em-main.broadcast4.you:443
PersistentKeepalive = 20
